---
title: "Analytics - Aula 05"
subtitle: "Regressão Múltipla"
author: "Layla Comparin"
output: html_notebook
---

```{r setup, include=FALSE}

#https://atom.io/

# Se as bibliotecas necessárias não estiveram instaladas, instale
if (!"readr" %in% installed.packages()) install.packages("readr")
if (!"dplyr" %in% installed.packages()) install.packages("dplyr")
if (!"ggplot2" %in% installed.packages()) install.packages("ggplot2")
if (!"haven" %in% installed.packages()) install.packages("haven")
#install.packages("texreg")

# Carregando as bibliotecas necessárias
library(readr)
library(dplyr)
library(ggplot2)
library(haven)
library(texreg)

# Carrega uma amostra da PNAD 2014

bd = read_sav("https://github.com/neylsoncrepalde/MODUS/blob/master/PNAD2014_30a50_novo4.sav?raw=true")
dim(bd)

```

Vamos implementar nosso primeiro modelo de regressão linear múltipla. Nesse modelo Y = isei88, x1 = anoesco, x2 = escpai.

```{r}
#Regressão 1
reg1 = lm(isei88 ~ anosesco, data = bd)
reg2 = lm(isei88 ~ escpai, data = bd)
reg3 = lm(isei88 ~ anosesco + escpai, data = bd)
screenreg(list(reg1, reg2, reg3))

# ==================================================
#              Model 1      Model 2      Model 3    
# --------------------------------------------------
# (Intercept)    15.79 ***    29.44 ***    15.72 *** (b0)
#                (0.54)       (0.37)       (0.52)   
# anosesco        2.47 ***                  2.02 *** (b1)
#                (0.05)                    (0.06)   
# escpai                       1.96 ***     0.89 *** (b2)
#                             (0.06)       (0.06)   
# --------------------------------------------------
# R^2             0.34         0.21         0.37    
# Adj. R^2        0.34         0.21         0.37    
# Num. obs.    4383         4383         4383       
# RMSE           14.87        16.31        14.51    
# ==================================================
# *** p < 0.001, ** p < 0.01, * p < 0.05

```

Testando os pressupostos do modelo:

Testando o pressuposto da normalidade dos erros:

```{r}
e= residuals(reg3)
b0 = reg3$coefficients[1]
b1 = reg3$coefficients[2]
b2 = reg3$coefficients[3]

ggplot(NULL, aes(e)) + geom_histogram() #Histograma
qqnorm(e) #Gráfico de probabilidade normal

```

